#
# Makefile for the nubia drivers.
#

obj-$(CONFIG_NUBIA_DISPLAY)           += display/
obj-$(CONFIG_NUBIA_FINGERPRINT)       += fingerprint/
obj-$(CONFIG_NUBIA_SENSORS)	      += sensors/
obj-$(CONFIG_NUBIA_TOUCHSCREENS)      += touch/
